<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Sale;
class SaleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {



        $sales = [
            [
                'id'=>26,
                'created_at'=>'2022-12-01 15:18:12',
                'sold_price' => 400,
                'company' => 'Cooler Master',
                'discount' => 0,
                'category_id' => 1,
                'amount' => 2,
                'color' => 'Black',
                'product_code' => 'dsfg34g35hg535h' ,
                'purchased_price' => 250,
                'product_id' => 1,
                'order_id' =>   11,
            ],
            [
                'id'=>27,
                'created_at'=>'2022-12-01 15:18:12',
                'sold_price' => 3200,
                'company' => 'AMD',
                'discount' => 0,
                'category_id' => 3,
                'amount' => 2,
                'color' => 'Black',
                'product_code' => 'd2hg4ji55hg535h' ,
                'purchased_price' => 2900,
                'product_id' => 15,
                'order_id' =>   11,
            ],
            [
                'id'=>28,
                'created_at'=>'2022-12-01 15:18:12',
                'sold_price' => 1450,
                'company' => 'ASUS',
                'discount' => 0,
                'category_id' => 6,
                'amount' => 2,
                'color' => 'Black',
                'product_code' => 'd21r4sdst5hu4z5h' ,
                'purchased_price' => 1300,
                'product_id' => 35,
                'order_id' =>   11,
            ],
            [
                'id'=>29,
                'created_at'=>'2022-12-02 15:18:12',
                'sold_price' => 600,
                'company' => 'CORSAIR',
                'discount' => 0,
                'category_id' => 5,
                'amount' => 1,
                'color' => 'Black',
                'product_code' => 'd2rry2225hu335h' ,
                'purchased_price' => 550,
                'product_id' => 28,
                'order_id' =>   12,
            ],
            [
                'id'=>30,
                'created_at'=>'2022-12-02 15:18:12',
                'sold_price' => 999,
                'company' => 'ASUS',
                'discount' => 0,
                'category_id' => 4,
                'amount' => 5,
                'color' => 'Black',
                'product_code' => 'd2hghji55hpp35h' ,
                'purchased_price' => 890,
                'product_id' => 19,
                'order_id' =>   12,
            ],
            [
                'id'=>31,
                'created_at'=>'2022-12-02 15:18:12',
                'sold_price' => 600,
                'company' => 'ASUS',
                'discount' => 0,
                'category_id' => 6,
                'amount' => 3,
                'color' => 'Black',
                'product_code' => 'd21r4sdst5hu445h' ,
                'purchased_price' => 550,
                'product_id' => 34,
                'order_id' =>   12,
            ],
            [
                'id'=>32,
                'created_at'=>'2022-12-03 15:18:12',
                'sold_price' => 350,
                'company' => 'RAZER',
                'discount' => 0,
                'category_id' => 2,
                'amount' => 4,
                'color' => 'Black',
                'product_code' => 'd2hg22g5ttt535h' ,
                'purchased_price' => 270,
                'product_id' => 8,
                'order_id' =>   13,
            ],
            [
                'id'=>33,
                'created_at'=>'2022-12-03 15:18:12',
                'sold_price' => 699,
                'company' => 'INTEL',
                'discount' => 0,
                'category_id' => 3,
                'amount' =>3,
                'color' => 'Black',
                'product_code' => 'd2hg4ji55hkk35h' ,
                'purchased_price' => 610,
                'product_id' => 16,
                'order_id' =>   13,
            ],
            [
                'id'=>34,
                'created_at'=>'2022-12-03 15:18:12',
                'sold_price' => 1200,
                'company' => 'ASUS',
                'discount' => 0,
                'category_id' => 4,
                'amount' => 2,
                'color' => 'Black',
                'product_code' => 'd2httji55huu35h' ,
                'purchased_price' => 990,
                'product_id' => 22,
                'order_id' =>   13,
            ],
            [
                'id'=>35,
                'created_at'=>'2022-12-04 15:18:12',
                'sold_price' => 190,
                'company' => 'RAZER',
                'discount' => 0,
                'category_id' => 2,
                'amount' => 3,
                'color' => 'Black',
                'product_code' => 'd2hg22g55hg535h' ,
                'purchased_price' => 120,
                'product_id' => 9,
                'order_id' =>   14,
            ],
            [
                'id'=>36,
                'created_at'=>'2022-12-04 15:18:12',
                'sold_price' => 200,
                'company' => 'COOLER MASTER',
                'discount' => 0,
                'category_id' => 2,
                'amount' => 3,
                'color' => 'Black',
                'product_code' => 'd2hgyyg55hg535h' ,
                'purchased_price' => 180,
                'product_id' => 9,
                'order_id' =>   14,
            ],
            [
                'id'=>37,
                'created_at'=>'2022-12-04 15:18:12',
                'sold_price' => 380,
                'company' => 'CORSAIR',
                'discount' => 0,
                'category_id' => 2,
                'amount' => 4,
                'color' => 'Black',
                'product_code' => 'd2hggtg55hg535h' ,
                'purchased_price' => 330,
                'product_id' => 12,
                'order_id' =>   14,
            ],
            [
                'id'=>38,
                'created_at'=>'2022-12-04 15:18:12',
                'sold_price' => 150,
                'company' => 'LOGITECH',
                'discount' => 0,
                'category_id' => 1,
                'amount' => 1,
                'color' => 'Black',
                'product_code' => 'dsfg34g55hg535h' ,
                'purchased_price' => 125,
                'product_id' => 3,
                'order_id' =>   14,
            ],
            [
                'id'=>39,
                'created_at'=>'2022-12-05 15:18:12',
                'sold_price' => 199,
                'company' => 'RAZER',
                'discount' => 0,
                'category_id' => 5,
                'amount' => 4,
                'color' => 'Black',
                'product_code' => 'd2rry4445hu335h' ,
                'purchased_price' => 175,
                'product_id' => 27,
                'order_id' =>   15,
            ],
            [
                'id'=>40,
                'created_at'=>'2022-12-05 15:18:12',
                'sold_price' => 950,
                'company' => 'AOC',
                'discount' => 0,
                'category_id' => 6,
                'amount' => 2,
                'color' => 'Black',
                'product_code' => 'd21rss2rh5hu445h' ,
                'purchased_price' => 800,
                'product_id' => 31,
                'order_id' =>   15,
            ],
            [
                'id'=>41,
                'created_at'=>'2022-12-05 15:18:12',
                'sold_price' => 350,
                'company' => 'HYPERX',
                'discount' => 0,
                'category_id' => 5,
                'amount' => 1,
                'color' => 'Black',
                'product_code' => 'd2rry22rh5ht465h' ,
                'purchased_price' => 290,
                'product_id' => 30,
                'order_id' =>   15,
            ],
            [
                'id'=>42,
                'created_at'=>'2022-12-06 15:18:12',
                'sold_price' => 300,
                'company' => 'LOGITECH',
                'discount' => 0,
                'category_id' => 2,
                'amount' => 2,
                'color' => 'Black',
                'product_code' => 'd2hgffg55hg535h' ,
                'purchased_price' => 250,
                'product_id' => 11,
                'order_id' =>   16,
            ],
            [
                'id'=>43,
                'created_at'=>'2022-12-06 15:18:12',
                'sold_price' => 245,
                'company' => 'RAZER',
                'discount' => 0,
                'category_id' => 1,
                'amount' => 2,
                'color' => 'Black',
                'product_code' => 'dgfg22g55hg535h' ,
                'purchased_price' => 200,
                'product_id' => 5,
                'order_id' =>   16,
            ],
            [
                'id'=>44,
                'created_at'=>'2022-12-06 15:18:12',
                'sold_price' => 1200,
                'company' => 'AMD',
                'discount' => 0,
                'category_id' => 3,
                'amount' => 1,
                'color' => 'Black',
                'product_code' => 'd2hg4rg55hg535h' ,
                'purchased_price' => 950,
                'product_id' => 13,
                'order_id' =>   16,
            ],
            [
                'id'=>45,
                'created_at'=>'2022-12-07 15:18:12',
                'sold_price' => 999,
                'company' => 'ASUS',
                'discount' => 0,
                'category_id' => 4,
                'amount' => 5,
                'color' => 'Black',
                'product_code' => 'd2hghji55hpp35h' ,
                'purchased_price' => 890,
                'product_id' => 19,
                'order_id' =>   17,
            ],
            [
                'id'=>46,
                'created_at'=>'2022-12-07 15:18:12',
                'sold_price' => 1200,
                'company' => 'INTEL',
                'discount' => 0,
                'category_id' => 3,
                'amount' => 6,
                'color' => 'Black',
                'product_code' => 'd2hg4ji55hpp35h' ,
                'purchased_price' => 1050,
                'product_id' => 18,
                'order_id' =>   17,
            ],
            [
                'id'=>47,
                'created_at'=>'2022-12-07 15:18:12',
                'sold_price' => 1600,
                'company' => 'ASUS',
                'discount' => 0,
                'category_id' => 4,
                'amount' => 2,
                'color' => 'White',
                'product_code' => 'd2httj125huu35h' ,
                'purchased_price' => 1490,
                'product_id' => 23,
                'order_id' =>   17,
            ],
            [
                'id'=>48,
                'created_at'=>'2022-12-08 15:18:12',
                'sold_price' => 1700,
                'company' => 'INTEL',
                'discount' => 0,
                'category_id' => 3,
                'amount' => 1,
                'color' => 'Black',
                'product_code' => 'd2hg4ji55hgl35h' ,
                'purchased_price' => 1500,
                'product_id' => 17,
                'order_id' =>   18,
            ],
            [
                'id'=>49,
                'created_at'=>'2022-12-08 15:18:12',
                'sold_price' => 999,
                'company' => 'GALAX',
                'discount' => 0,
                'category_id' => 4,
                'amount' => 5,
                'color' => 'Black',
                'product_code' => 'd2hghji55huu35h' ,
                'purchased_price' => 890,
                'product_id' => 21,
                'order_id' =>   18,
            ],
            [
                'id'=>50,
                'created_at'=>'2022-12-08 15:18:12',
                'sold_price' => 1600,
                'company' => 'ASUS',
                'discount' => 0,
                'category_id' => 4,
                'amount' => 1,
                'color' => 'Black',
                'product_code' => 'd2hghji55huu35h' ,
                'purchased_price' => 1490,
                'product_id' => 24,
                'order_id' =>   18,
            ],
            [
                'id'=>51,
                'created_at'=>'2022-12-09 15:18:12',
                'sold_price' => 600,
                'company' => 'CORSAIR',
                'discount' => 0,
                'category_id' => 5,
                'amount' => 5,
                'color' => 'White',
                'product_code' => 'd2rry2225hu335h' ,
                'purchased_price' => 550,
                'product_id' => 28,
                'order_id' =>   19,
            ],
            [
                'id'=>52,
                'created_at'=>'2022-12-09 15:18:12',
                'sold_price' => 220,
                'company' => 'CREATIVE',
                'discount' => 0,
                'category_id' => 5,
                'amount' => 1,
                'color' => 'Black',
                'product_code' => 'd2htyp125hu335h' ,
                'purchased_price' => 200,
                'product_id' => 25,
                'order_id' =>   19,
            ],
            [
                'id'=>53,
                'created_at'=>'2022-12-09 15:18:12',
                'sold_price' => 180,
                'company' => 'LOGITECH',
                'discount' => 0,
                'category_id' => 5,
                'amount' => 8,
                'color' => 'Black',
                'product_code' => 'd2rryp125hu335h' ,
                'purchased_price' => 165,
                'product_id' => 26,
                'order_id' =>   19,
            ],
            [
                'id'=>54,
                'created_at'=>'2022-12-10 15:18:12',
                'sold_price' => 1200,
                'company' => 'GIGABYTE',
                'discount' => 0,
                'category_id' => 6,
                'amount' => 1,
                'color' => 'Black',
                'product_code' => 'd21r4sdst5hu4aah' ,
                'purchased_price' => 990,
                'product_id' => 36,
                'order_id' =>   20,
            ],
            [
                'id'=>55,
                'created_at'=>'2022-12-10 15:18:12',
                'sold_price' => 1500,
                'company' => 'ASUS',
                'discount' => 0,
                'category_id' => 6,
                'amount' => 1,
                'color' => 'Black',
                'product_code' => 'd21r4sfdd5hu445h' ,
                'purchased_price' => 1410,
                'product_id' => 33,
                'order_id' =>   20,
            ],
            [
                'id'=>56,
                'created_at'=>'2022-12-10 15:18:12',
                'sold_price' => 1450,
                'company' => 'ASUS',
                'discount' => 0,
                'category_id' => 6,
                'amount' => 1,
                'color' => 'Black',
                'product_code' => 'd21r4sdst5hu4z5h' ,
                'purchased_price' => 1300,
                'product_id' => 35,
                'order_id' =>   20,
            ],
            [
                'id'=>57,
                'created_at'=>'2022-12-10 15:18:12',
                'sold_price' => 850,
                'company' => 'AOC',
                'discount' => 0,
                'category_id' => 6,
                'amount' => 5,
                'color' => 'Black',
                'product_code' => 'd21rss23gyhu445h' ,
                'purchased_price' => 700,
                'product_id' => 32,
                'order_id' =>   20,
            ],


        ];



        foreach ($sales as $sale)

            Sale::create(
                $sale

            );
    }
}
